### PR TITLE
Reverse class

### PR DESCRIPTION
**Pull request by joshia5**
Merge reverse class APIs

### CODE REVIEW

**Comment by joshia5** [comment]
@cwsmith the reverseClass branch standalone as well as merged-with-master builds and passes ctest on local system with and without cuda.
the github action for g++ just says 'cancelled'. Do you want me to merge this anyway?

**Comment by cwsmith** [comment]
@joshia5 The operating system used by the github actions updated since a test was last run.  The update brought in GCC 9 and Clang 10 compilers.  Omega_h does not compile with Clang 10 so when it failed it killed ('cancelled') the GCC build, which we expect to succeed.  I just pushed a possible fix to master.  If you don't mind I'll merge that into this branch and see if that fixes the automated builds and checks.

**Comment by joshia5** [comment]
@cwsmith sure. my knowledge of cmake, build systems and github actions is quite limited as you know, so i was concerned about the unexpected build behavior.

**Comment by cwsmith** [comment]
@joshia5 Is there a problem creating the reverse classification arrays on the GPU?

**Pull request merged**
