### PR TITLE
enabled initializer list constructor for omega_h_vector on cuda

### PR DESCRIPTION
**Pull request by MagentaTreehouse**

### CODE REVIEW

**Comment by cwsmith** [comment]
Thank you for the contribution.  Is there a minimum version of CUDA required for this?

**Comment by jacobmerson** [comment]
I believe the minimum is CUDA 7.0

**Comment by jacobmerson** [comment]
First docs I can find with reference is [CUDA 8.0](https://docs.nvidia.com/cuda/archive/8.0/cuda-c-programming-guide/index.html#initializer-list) CUDA 7.0 programming guide is hard to come by.

Kokkos folks mention that it is available in CUDA 7.0 [here](https://github.com/kokkos/kokkos/issues/611)

**Comment by cwsmith** [comment]
OK.  Thank you.  At some point we may want to test those older versions but given that they are not available on most machines we work with, I think it is safe to proceed.  I'll merge this now.

**Pull request merged**
