### PR TITLE
attempt to work around HIP errors

### PR DESCRIPTION
**Pull request by ibaned**
@cwsmith let me know if this improves anything...

### CODE REVIEW

**Comment by cwsmith** [comment]
Thanks Dan.  I'm not sure if this helped yet.  It has spawned a new, earlier, error in `Omega_h_adj.cpp`.  Below is the log from the build prior to a757fa3 (b7add7f):

```
make[2]: Entering directory `/g/g19/smith516/develop/build-omega-rocm35'
[  0%] Building CXX object src/CMakeFiles/omega_h.dir/Omega_h_adapt.cpp.o
cd /g/g19/smith516/develop/build-omega-rocm35/src && /opt/rocm-3.6.0/bin/hipcc   -I/g/g19/smith516/develop/omega_h/src -I/g/g19/smith516/develop/build-omega-rocm35/src -I/g/g19/smith516/develop/omega_h/tpl  --amdgpu-target=gfx906   -std=c++11 -o CMakeFiles/omega_h.dir/Omega_h_adapt.cpp.o -c /g/g19/smith516/develop/omega_h/src/Omega_h_adapt.cpp
[  1%] Building CXX object src/CMakeFiles/omega_h.dir/Omega_h_adj.cpp.o
cd /g/g19/smith516/develop/build-omega-rocm35/src && /opt/rocm-3.6.0/bin/hipcc   -I/g/g19/smith516/develop/omega_h/src -I/g/g19/smith516/develop/build-omega-rocm35/src -I/g/g19/smith516/develop/omega_h/tpl  --amdgpu-target=gfx906   -std=c++11 -o CMakeFiles/omega_h.dir/Omega_h_adj.cpp.o -c /g/g19/smith516/develop/omega_h/src/Omega_h_adj.cpp
[  1%] Building CXX object src/CMakeFiles/omega_h.dir/Omega_h_align.cpp.o
cd /g/g19/smith516/develop/build-omega-rocm35/src && /opt/rocm-3.6.0/bin/hipcc   -I/g/g19/smith516/develop/omega_h/src -I/g/g19/smith516/develop/build-omega-rocm35/src -I/g/g19/smith516/develop/omega_h/tpl  --amdgpu-target=gfx906   -std=c++11 -o CMakeFiles/omega_h.dir/Omega_h_align.cpp.o -c /g/g19/smith516/develop/omega_h/src/Omega_h_align.cpp
[  2%] Building CXX object src/CMakeFiles/omega_h.dir/Omega_h_amr.cpp.o
cd /g/g19/smith516/develop/build-omega-rocm35/src && /opt/rocm-3.6.0/bin/hipcc   -I/g/g19/smith516/develop/omega_h/src -I/g/g19/smith516/develop/build-omega-rocm35/src -I/g/g19/smith516/develop/omega_h/tpl  --amdgpu-target=gfx906   -std=c++11 -o CMakeFiles/omega_h.dir/Omega_h_amr.cpp.o -c /g/g19/smith516/develop/omega_h/src/Omega_h_amr.cpp
[  2%] Building CXX object src/CMakeFiles/omega_h.dir/Omega_h_amr_topology.cpp.o
cd /g/g19/smith516/develop/build-omega-rocm35/src && /opt/rocm-3.6.0/bin/hipcc   -I/g/g19/smith516/develop/omega_h/src -I/g/g19/smith516/develop/build-omega-rocm35/src -I/g/g19/smith516/develop/omega_h/tpl  --amdgpu-target=gfx906   -std=c++11 -o CMakeFiles/omega_h.dir/Omega_h_amr_topology.cpp.o -c /g/g19/smith516/develop/omega_h/src/Omega_h_amr_topology.cpp
[  3%] Building CXX object src/CMakeFiles/omega_h.dir/Omega_h_amr_transfer.cpp.o
cd /g/g19/smith516/develop/build-omega-rocm35/src && /opt/rocm-3.6.0/bin/hipcc   -I/g/g19/smith516/develop/omega_h/src -I/g/g19/smith516/develop/build-omega-rocm35/src -I/g/g19/smith516/develop/omega_h/tpl  --amdgpu-target=gfx906   -std=c++11 -o CMakeFiles/omega_h.dir/Omega_h_amr_transfer.cpp.o -c /g/g19/smith516/develop/omega_h/src/Omega_h_amr_transfer.cpp
[  3%] Building CXX object src/CMakeFiles/omega_h.dir/Omega_h_any.cpp.o
cd /g/g19/smith516/develop/build-omega-rocm35/src && /opt/rocm-3.6.0/bin/hipcc   -I/g/g19/smith516/develop/omega_h/src -I/g/g19/smith516/develop/build-omega-rocm35/src -I/g/g19/smith516/develop/omega_h/tpl  --amdgpu-target=gfx906   -std=c++11 -o CMakeFiles/omega_h.dir/Omega_h_any.cpp.o -c /g/g19/smith516/develop/omega_h/src/Omega_h_any.cpp
[  4%] Building CXX object src/CMakeFiles/omega_h.dir/Omega_h_approach.cpp.o
cd /g/g19/smith516/develop/build-omega-rocm35/src && /opt/rocm-3.6.0/bin/hipcc   -I/g/g19/smith516/develop/omega_h/src -I/g/g19/smith516/develop/build-omega-rocm35/src -I/g/g19/smith516/develop/omega_h/tpl  --amdgpu-target=gfx906   -std=c++11 -o CMakeFiles/omega_h.dir/Omega_h_approach.cpp.o -c /g/g19/smith516/develop/omega_h/src/Omega_h_approach.cpp
[  4%] Building CXX object src/CMakeFiles/omega_h.dir/Omega_h_array.cpp.o
cd /g/g19/smith516/develop/build-omega-rocm35/src && /opt/rocm-3.6.0/bin/hipcc   -I/g/g19/smith516/develop/omega_h/src -I/g/g19/smith516/develop/build-omega-rocm35/src -I/g/g19/smith516/develop/omega_h/tpl  --amdgpu-target=gfx906   -std=c++11 -o CMakeFiles/omega_h.dir/Omega_h_array.cpp.o -c /g/g19/smith516/develop/omega_h/src/Omega_h_array.cpp
In file included from /g/g19/smith516/develop/omega_h/src/Omega_h_array.cpp:1:
/g/g19/smith516/develop/omega_h/src/Omega_h_array.hpp:283:1: error: no matching constructor for initialization of 'Write<signed char>'
OMEGA_H_EXPL_INST_DECL(I8)
^~~~~~~~~~~~~~~~~~~~~~~~~~
/g/g19/smith516/develop/omega_h/src/Omega_h_array.hpp:278:25: note: expanded from macro 'OMEGA_H_EXPL_INST_DECL'
  extern template class HostWrite<T>;                                          \   
                        ^~~~~~~~~
```

Note, `Omega_h_adj.cpp` compiles without error before `Omega_h_array.cpp`.   Below is the new error (with a757fa3 merged)  in `Omega_h_adj.cpp`:

```
make[2]: Entering directory `/g/g19/smith516/develop/build-omega-rocm35'
cd /g/g19/smith516/develop/build-omega-rocm35 && /usr/tce/packages/cmake/cmake-3.14.5/bin/cmake -E cmake_depends "Unix Makefiles" /g/g19/smith516/develop/omega_h /g/g19/smith516/develop/omega_h/src /g/g19/smith516/develop/build-omega-rocm35 /g/g19/smith516/develop/build-omega-rocm35/src /g/g19/smith516/develop/build-omega-rocm35/src/CMakeFiles/omega_h.dir/DependInfo.cmake --color=
Dependee "/g/g19/smith516/develop/build-omega-rocm35/src/CMakeFiles/omega_h.dir/DependInfo.cmake" is newer than depender "/g/g19/smith516/develop/build-omega-rocm35/src/CMakeFiles/omega_h.dir/depend.internal".
Dependee "/g/g19/smith516/develop/build-omega-rocm35/src/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/g/g19/smith516/develop/build-omega-rocm35/src/CMakeFiles/omega_h.dir/depend.internal".
Scanning dependencies of target omega_h
make[2]: Leaving directory `/g/g19/smith516/develop/build-omega-rocm35'
make -f src/CMakeFiles/omega_h.dir/build.make src/CMakeFiles/omega_h.dir/build
make[2]: Entering directory `/g/g19/smith516/develop/build-omega-rocm35'
[  0%] Building CXX object src/CMakeFiles/omega_h.dir/Omega_h_adapt.cpp.o
cd /g/g19/smith516/develop/build-omega-rocm35/src && /opt/rocm-3.6.0/bin/hipcc   -I/g/g19/smith516/develop/omega_h/src -I/g/g19/smith516/develop/build-omega-rocm35/src -I/g/g19/smith516/develop/omega_h/tpl  --amdgpu-target=gfx906   -std=c++11 -o CMakeFiles/omega_h.dir/Omega_h_adapt.cpp.o -c /g/g19/smith516/develop/omega_h/src/Omega_h_adapt.cpp
[  1%] Building CXX object src/CMakeFiles/omega_h.dir/Omega_h_adj.cpp.o
cd /g/g19/smith516/develop/build-omega-rocm35/src && /opt/rocm-3.6.0/bin/hipcc   -I/g/g19/smith516/develop/omega_h/src -I/g/g19/smith516/develop/build-omega-rocm35/src -I/g/g19/smith516/develop/omega_h/tpl  --amdgpu-target=gfx906   -std=c++11 -o CMakeFiles/omega_h.dir/Omega_h_adj.cpp.o -c /g/g19/smith516/develop/omega_h/src/Omega_h_adj.cpp
/g/g19/smith516/develop/omega_h/src/Omega_h_adj.cpp:394:12: error: object of type 'Write<Omega_h::LO>' (aka 'Write<int>') cannot be assigned because its copy assignment operator is implicitly deleted
  *a2b_out = a2b;
           ^
/g/g19/smith516/develop/omega_h/src/Omega_h_array.hpp:44:3: note: copy assignment operator is implicitly deleted because 'Write<int>' has a user-declared move constructor
  Write(Write&&) = default;
  ^
/g/g19/smith516/develop/omega_h/src/Omega_h_adj.cpp:395:14: error: object of type 'Write<Omega_h::I8>' (aka 'Write<signed char>') cannot be assigned because its copy assignment operator is implicitly deleted
  *codes_out = codes;
             ^
/g/g19/smith516/develop/omega_h/src/Omega_h_array.hpp:44:3: note: copy assignment operator is implicitly deleted because 'Write<signed char>' has a user-declared move constructor
  Write(Write&&) = default;
  ^
/g/g19/smith516/develop/omega_h/src/Omega_h_adj.cpp:470:11: error: object of type 'Write<Omega_h::I8>' (aka 'Write<signed char>') cannot be assigned because its copy assignment operator is implicitly deleted
    codes = Write<I8>(hl2l.size(), codes_name);
          ^
/g/g19/smith516/develop/omega_h/src/Omega_h_array.hpp:44:3: note: copy assignment operator is implicitly deleted because 'Write<signed char>' has a user-declared move constructor
  Write(Write&&) = default;
  ^
3 errors generated when compiling for gfx906.
make[2]: *** [src/CMakeFiles/omega_h.dir/Omega_h_adj.cpp.o] Error 1
make[2]: Leaving directory `/g/g19/smith516/develop/build-omega-rocm35'
make[1]: *** [src/CMakeFiles/omega_h.dir/all] Error 2
make[1]: Leaving directory `/g/g19/smith516/develop/build-omega-rocm35'
make: *** [all] Error 2
```

**Comment by cwsmith** [comment]
Adding the following default copy assignment operator to `Write` gets past the `Omega_h_adj.cpp` error:

```
diff --git a/src/Omega_h_array.hpp b/src/Omega_h_array.hpp
index 72f6e6e..aabe75e 100644
--- a/src/Omega_h_array.hpp
+++ b/src/Omega_h_array.hpp
@@ -43,6 +43,7 @@ class Write {
 #endif
   Write(Write&&) = default;
   Write(Write const&) = default;
+  Write& operator=(const Write&) = default;
   Write(LO size_in, std::string const& name = "");
   Write(LO size_in, T value, std::string const& name = "");
   Write(LO size_in, T offset, T stride, std::string const& name = "");
```

Compilation is **very** slow... it has  gotten past `Omega_h_array.cpp` though.

**Comment by cwsmith** [comment]
.... and the compiler failed

```
[ 48%] Building CXX object src/CMakeFiles/omega_h.dir/Omega_h_swap3d.cpp.o
[ 48%] Building CXX object src/CMakeFiles/omega_h.dir/Omega_h_swap3d_qualities.cpp.o
LLVM ERROR: Unsupported expression in static initializer: addrspacecast ([3 x i32] addrspace(4)* getelementptr inbounds ([1 x [3 x i32]], [1 x [3 x i32]] addrspace(4)* @_ZN7Omega_h6swap3dL11triangles_3E, i64 0, i64 0) to [3 x i32]*)
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.      Program arguments: /opt/rocm-3.6.0/llvm/bin/llc /var/tmp/smith516/Omega_h_swap3d_qualities-8cc0a2-gfx906-optimized-b86a2c.bc -O3 -mtriple=amdgcn-amd-amdhsa -mcpu=gfx906 -filetype=obj -amdgpu-early-inline-all=true -amdgpu-function-calls=false -o /var/tmp/smith516/Omega_h_swap3d_qualities-8cc0a2-gfx906-6aaa21.o 
1.      Running pass 'CallGraph Pass Manager' on module '/var/tmp/smith516/Omega_h_swap3d_qualities-8cc0a2-gfx906-optimized-b86a2c.bc'.
 #0 0x000000000199f16a llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/opt/rocm-3.6.0/llvm/bin/llc+0x199f16a)
 #1 0x000000000199d064 llvm::sys::RunSignalHandlers() (/opt/rocm-3.6.0/llvm/bin/llc+0x199d064)
 #2 0x000000000199d1a3 SignalHandler(int) (/opt/rocm-3.6.0/llvm/bin/llc+0x199d1a3)
 #3 0x00002aaaaacde630 __restore_rt (/lib64/libpthread.so.0+0xf630)
 #4 0x00002aaaabf8c387 raise /usr/src/debug/glibc-2.17-c758a686/signal/../nptl/sysdeps/unix/sysv/linux/raise.c:55:0
 #5 0x00002aaaabf8da78 abort /usr/src/debug/glibc-2.17-c758a686/stdlib/abort.c:92:0
 #6 0x000000000192a340 llvm::report_fatal_error(llvm::Twine const&, bool) (/opt/rocm-3.6.0/llvm/bin/llc+0x192a340)
 #7 0x000000000192a4ae (/opt/rocm-3.6.0/llvm/bin/llc+0x192a4ae)
 #8 0x0000000000db2d6a llvm::AsmPrinter::lowerConstant(llvm::Constant const*) (/opt/rocm-3.6.0/llvm/bin/llc+0xdb2d6a)
 #9 0x0000000000db2ade llvm::AsmPrinter::lowerConstant(llvm::Constant const*) (/opt/rocm-3.6.0/llvm/bin/llc+0xdb2ade)
#10 0x0000000000db86e3 emitGlobalConstantImpl(llvm::DataLayout const&, llvm::Constant const*, llvm::AsmPrinter&, llvm::Constant const*, unsigned long) (/opt/rocm-3.6.0/llvm/bin/llc+0xdb86e3)
#11 0x0000000000db8cfe emitGlobalConstantImpl(llvm::DataLayout const&, llvm::Constant const*, llvm::AsmPrinter&, llvm::Constant const*, unsigned long) (/opt/rocm-3.6.0/llvm/bin/llc+0xdb8cfe)
#12 0x0000000000dbb08a llvm::AsmPrinter::emitGlobalVariable(llvm::GlobalVariable const*) (/opt/rocm-3.6.0/llvm/bin/llc+0xdbb08a)
#13 0x00000000006f08bf llvm::AMDGPUAsmPrinter::emitGlobalVariable(llvm::GlobalVariable const*) (/opt/rocm-3.6.0/llvm/bin/llc+0x6f08bf)
#14 0x0000000000db6c7a llvm::AsmPrinter::doFinalization(llvm::Module&) (/opt/rocm-3.6.0/llvm/bin/llc+0xdb6c7a)
#15 0x0000000001317fac llvm::FPPassManager::doFinalization(llvm::Module&) (.localalias.492) (/opt/rocm-3.6.0/llvm/bin/llc+0x1317fac)
#16 0x0000000000c2fbbc (anonymous namespace)::CGPassManager::runOnModule(llvm::Module&) (/opt/rocm-3.6.0/llvm/bin/llc+0xc2fbbc)
#17 0x00000000013237d6 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/opt/rocm-3.6.0/llvm/bin/llc+0x13237d6)
#18 0x00000000006b25c3 compileModule(char**, llvm::LLVMContext&) (/opt/rocm-3.6.0/llvm/bin/llc+0x6b25c3)
#19 0x0000000000647b15 main (/opt/rocm-3.6.0/llvm/bin/llc+0x647b15)
#20 0x00002aaaabf78555 __libc_start_main /usr/src/debug/glibc-2.17-c758a686/csu/../csu/libc-start.c:300:0
#21 0x00000000006ac4f5 _start (/opt/rocm-3.6.0/llvm/bin/llc+0x6ac4f5)
clang-11: error: unable to execute command: Aborted (core dumped)
clang-11: error: amdgcn-link command failed due to signal (use -v to see invocation)
clang version 11.0.0 (/data/jenkins_workspace/centos_pipeline_job_3.6/rocm-rel-3.6/rocm-3.6-43-20200704/7.5/external/llvm-project/clang f7b7e21a21d08df6971d2c77315a0e41b7639334)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm-3.6.0/llvm/bin
clang-11: note: diagnostic msg: Error generating preprocessed source(s).
make[2]: *** [src/CMakeFiles/omega_h.dir/Omega_h_swap3d_qualities.cpp.o] Error 254
make[1]: *** [src/CMakeFiles/omega_h.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by cwsmith** [comment]
I'll merged this PR, commit the addition of the copy assignment operator, and create an issue on the rocm page for the llvm failure.

**Comment by ibaned** [comment]
Oh I didn't see the other comments. I opened #2 which has a slightly more complete fix.

**Comment by cwsmith** [comment]
No worries.  Thank you for the fixes.  I suspect these fixes (in either form) are unrelated to the compiler error.

**Pull request merged**
